DROP TABLE Fall24_S003_T9_Validated_By CASCADE CONSTRAINTS;
DROP TABLE Fall24_S003_T9_Report CASCADE CONSTRAINTS;
DROP TABLE Fall24_S003_T9_Administrator CASCADE CONSTRAINTS;
DROP TABLE Fall24_S003_T9_Keeps CASCADE CONSTRAINTS;
DROP TABLE Fall24_S003_T9_Produces CASCADE CONSTRAINTS;
DROP TABLE Fall24_S003_T9_Consumes CASCADE CONSTRAINTS;
DROP TABLE Fall24_S003_T9_Food_Leftover CASCADE CONSTRAINTS;
DROP TABLE Fall24_S003_T9_Food_item CASCADE CONSTRAINTS;
DROP TABLE Fall24_S003_T9_Attendance_Record_date CASCADE CONSTRAINTS;
DROP TABLE Fall24_S003_T9_Attendance_record CASCADE CONSTRAINTS;
DROP TABLE Fall24_S003_T9_Event_Location CASCADE CONSTRAINTS;
DROP TABLE Fall24_S003_T9_Event CASCADE CONSTRAINTS;
DROP TABLE Fall24_S003_T9_Attendee CASCADE CONSTRAINTS;



--OUTPUT 

-- SQL> DROP TABLE Fall24_S003_T9_Validated_By CASCADE CONSTRAINTS;

-- Table dropped.

-- SQL> DROP TABLE Fall24_S003_T9_Report CASCADE CONSTRAINTS;

-- Table dropped.

-- SQL> DROP TABLE Fall24_S003_T9_Administrator CASCADE CONSTRAINTS;

-- Table dropped.

-- SQL> DROP TABLE Fall24_S003_T9_Keeps CASCADE CONSTRAINTS;

-- Table dropped.

-- SQL> DROP TABLE Fall24_S003_T9_Produces CASCADE CONSTRAINTS;

-- Table dropped.

-- SQL> DROP TABLE Fall24_S003_T9_Consumes CASCADE CONSTRAINTS;

-- Table dropped.

-- SQL> DROP TABLE Fall24_S003_T9_Food_Leftover CASCADE CONSTRAINTS;

-- Table dropped.

-- SQL> DROP TABLE Fall24_S003_T9_Food_item CASCADE CONSTRAINTS;

-- Table dropped.

-- SQL> DROP TABLE Fall24_S003_T9_Attendance_Record_date CASCADE CONSTRAINTS;

-- Table dropped.

-- SQL> DROP TABLE Fall24_S003_T9_Attendance_record CASCADE CONSTRAINTS;

-- Table dropped.

-- SQL> DROP TABLE Fall24_S003_T9_Event_Location CASCADE CONSTRAINTS;

-- Table dropped.

-- SQL> DROP TABLE Fall24_S003_T9_Event CASCADE CONSTRAINTS;

-- Table dropped.

-- SQL> DROP TABLE Fall24_S003_T9_Attendee CASCADE CONSTRAINTS;

-- Table dropped.

-- SQL> spool off
